name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TREENUT }}

      - name: Build and push Nginx image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nginx:latest
            ghcr.io/${{ github.repository_owner }}/nginx:${{ github.ref_name }}

      - name: Build and push FastAPI image
        uses: docker/build-push-action@v2
        with:
          context: ./fastapi
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/fastapi:latest
            ghcr.io/${{ github.repository_owner }}/fastapi:${{ github.ref_name }}

      - name: Build and push MySQL image
        uses: docker/build-push-action@v2
        with:
          context: ./mysql
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mysql:latest
            ghcr.io/${{ github.repository_owner }}/mysql:${{ github.ref_name }}

      - name: Build and push MongoDB image
        uses: docker/build-push-action@v2
        with:
          context: ./mongo
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mongodb:latest
            ghcr.io/${{ github.repository_owner }}/mongodb:${{ github.ref_name }}
